appName: tbsi-demo-test-a-app

image:
  pullPolicy: Always
  # pullSecret: docker-hub-private
  repository: arahmane/backend-a:latest #modif from workflow

hpa:
  name: tbsi-demo-test-a-app
  max: 3
  min: 1
  targetCPU: 60

ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: tbsi-demo-test-a-app
  host: backend-a.slimebox.my.id

namespace: tbsi

resources:
  requests:
    cpu: 50m
    memory: 50Mi

secret:
  vmountName: tbsi-demo-test-a-app
  vmountPath: /.env
  volumeName: tbsi-demo-test-a-app
  secretName: env-tbsi-demo-test-a

restartPolicy: Always

service: 
  externalPort: 3001
  internalPort: 3001
  name: tbsi-demo-test-a-app
  port: 3001
  protocol: TCP
  type: ClusterIP

strategy:
  surge: 1
  type: RollingUpdate
  unavailable: 25%