apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # labels:
  #   app.kubernetes.io/name: devops-blue
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx # not yet on before version
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.externalPort }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.secretName }}
